set shell := ["bash", "-ceu"]
set dotenv-load := true

local_database_url := "postgres://learning:learning@localhost:54329/learning"
test_database_url := "postgres://learning:learning@localhost:54330/learning"
prod_env := "config/op/prod.envmap"
prod_rds_env := "config/op/prod-rds.envmap"
dev_token_ref := "op://ai-agent-army/OnePasswordDevServiceAccount/SERVICE_ACCOUNT_PASSWORD"
prod_keys := "PGHOST PGPORT PGDATABASE PGUSER PGPASSWORD PGSSLMODE"
prod_admin_keys := "POSTGRES_ADMIN_HOST POSTGRES_ADMIN_PORT POSTGRES_ADMIN_DATABASE POSTGRES_ADMIN_USER POSTGRES_ADMIN_PASSWORD POSTGRES_ADMIN_SSLMODE"
prod_rds_keys := "AWS_REGION RDS_STACK_NAME RDS_INSTANCE_IDENTIFIER RDS_DB_INSTANCE_CLASS RDS_ALLOCATED_STORAGE RDS_MAX_ALLOCATED_STORAGE RDS_SUBNET_GROUP_NAME RDS_SECURITY_GROUP_IDS"

default:
    @just --list

require-pnpm:
    @command -v pnpm >/dev/null || { echo "pnpm is required."; exit 1; }

_require-op:
    @command -v op >/dev/null || { echo "1Password CLI ('op') is required."; exit 1; }

require-psql:
    @command -v psql >/dev/null || { echo "psql is required. Install PostgreSQL client tools first."; exit 1; }

require-aws:
    @command -v aws >/dev/null || { echo "AWS CLI is required."; exit 1; }
    @aws sts get-caller-identity >/dev/null || { echo "AWS CLI is not authenticated."; exit 1; }

# Verify required env vars are present and resolved (not still `op://...`).
#   just check-env "PGHOST PGPORT PGDATABASE PGUSER PGPASSWORD PGSSLMODE"
check-env KEYS:
    #!/usr/bin/env bash
    set -euo pipefail
    missing=()
    for key in {{ KEYS }}; do
        val="${!key:-}"
        if [[ -z "$val" || "$val" == op://* ]]; then
            missing+=("$key")
        fi
    done
    if (( ${#missing[@]} )); then
        echo "ERROR: missing/unresolved env vars: ${missing[*]}" >&2
        echo "  Run: just load-dev-token" >&2
        echo "  Then: just setup-env" >&2
        exit 1
    fi

_ensure-env KEYS:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! just check-env "{{ KEYS }}" >/dev/null 2>&1; then
        if [[ -n "${AI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN:-${OP_SERVICE_ACCOUNT_TOKEN:-}}" ]]; then
            echo "[env] Hydrating local secrets from 1Password..."
            just setup-env
        else
            just check-env "{{ KEYS }}"
        fi
    fi
    just check-env "{{ KEYS }}"

# Seed .env with the ai-agent-army-dev service account token.
# Run once per machine; requires interactive 1Password access to the bootstrap item.
load-dev-token: _require-op
    #!/usr/bin/env bash
    set -euo pipefail
    token="$(op read "{{ dev_token_ref }}")"
    if [[ -z "$token" ]]; then
        echo "1Password returned an empty service account token from {{ dev_token_ref }}" >&2
        exit 1
    fi
    tmp="$(mktemp)"
    if [[ -f .env ]]; then
        grep -v '^AI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN=' .env > "$tmp" || true
    fi
    printf '\nAI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN=%s\n' "$token" >> "$tmp"
    mv "$tmp" .env
    chmod 600 .env
    echo "[ok] AI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN written to .env"

# Materialize prod and RDS secrets into .env using the ai-agent-army-dev service account.
setup-env: _require-op
    #!/usr/bin/env bash
    set -euo pipefail
    token="${AI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN:-${OP_SERVICE_ACCOUNT_TOKEN:-}}"
    if [[ -z "$token" ]]; then
        echo "AI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN is missing. Run: just load-dev-token" >&2
        exit 1
    fi
    tmp="$(mktemp)"
    prod_tmp="$(mktemp)"
    rds_tmp="$(mktemp)"
    trap 'rm -f "$tmp" "$prod_tmp" "$rds_tmp"' EXIT
    OP_SERVICE_ACCOUNT_TOKEN="$token" op inject -f -i "{{ prod_env }}" -o "$prod_tmp" >/dev/null
    OP_SERVICE_ACCOUNT_TOKEN="$token" op inject -f -i "{{ prod_rds_env }}" -o "$rds_tmp" >/dev/null
    {
        printf '# Generated by: just setup-env\n'
        printf '# Do not commit this file.\n\n'
        grep -v '^AI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN=' "$prod_tmp" || true
        printf '\n'
        grep -v '^AI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN=' "$rds_tmp" || true
        printf '\nAI_AGENT_ARMY_DEV_SERVICE_ACCOUNT_TOKEN=%s\n' "$token"
    } > "$tmp"
    mv "$tmp" .env
    chmod 600 .env
    trap - EXIT
    rm -f "$prod_tmp" "$rds_tmp"
    echo "[ok] .env written from {{ prod_env }} and {{ prod_rds_env }}"

# Local development database: Docker Postgres on localhost:54329.
db-up-local: require-pnpm
    @pnpm db:up

db-url-local:
    @echo "{{ local_database_url }}"

db-check-local: require-psql
    @psql "{{ local_database_url }}" --set=ON_ERROR_STOP=1 --command "select current_database(), current_user, version();"

db-migrate-local: require-pnpm
    @DATABASE_URL="{{ local_database_url }}" pnpm db:migrate

db-seed-local: require-pnpm
    @DATABASE_URL="{{ local_database_url }}" pnpm db:seed

db-reset-local: require-pnpm
    @DATABASE_URL="{{ local_database_url }}" DB_TARGET=local pnpm db:reset

db-shell-local: require-psql
    @psql "{{ local_database_url }}"

db-studio-local: require-pnpm
    @DATABASE_URL="{{ local_database_url }}" pnpm db:studio

dev-local: require-pnpm
    @DATABASE_URL="{{ local_database_url }}" pnpm dev

dev:
    @just dev-local

# Local test database: Docker Postgres on localhost:54330. Tests may truncate data.
db-up-test: require-pnpm
    @pnpm db:test:up

db-url-test:
    @echo "{{ test_database_url }}"

db-migrate-test: require-pnpm
    @DATABASE_URL="{{ test_database_url }}" pnpm db:migrate

db-reset-test: require-pnpm
    @DATABASE_URL="{{ test_database_url }}" DB_TARGET=test pnpm db:reset

test: require-pnpm
    @just db-up-test
    @just db-migrate-test
    @DATABASE_URL="{{ test_database_url }}" pnpm test

test-watch: require-pnpm
    @just db-up-test
    @just db-migrate-test
    @DATABASE_URL="{{ test_database_url }}" pnpm test:watch

ci: require-pnpm
    @just typecheck
    @just test
    @just build-local

# Production database: remote AWS RDS through hydrated .env secrets.
check-env-prod:
    @just _ensure-env "{{ prod_keys }}"
    @just --quiet check-env "{{ prod_keys }}"
    @echo "prod database environment is configured"

db-url-prod:
    @just _ensure-env "{{ prod_keys }}"
    @just --quiet _db-url-prod

_db-url-prod:
    @echo "postgresql://${PGUSER}:REDACTED@${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=${PGSSLMODE}"

db-url-admin-prod:
    @just _ensure-env "{{ prod_admin_keys }}"
    @just --quiet _db-url-admin-prod

_db-url-admin-prod:
    @echo "postgresql://${POSTGRES_ADMIN_USER}:REDACTED@${POSTGRES_ADMIN_HOST}:${POSTGRES_ADMIN_PORT}/${POSTGRES_ADMIN_DATABASE}?sslmode=${POSTGRES_ADMIN_SSLMODE}"

db-check-prod: require-psql
    @just _ensure-env "{{ prod_keys }}"
    @just _db-check-prod

_db-check-prod:
    @psql "host=$PGHOST port=$PGPORT dbname=$PGDATABASE user=$PGUSER sslmode=$PGSSLMODE" --set=ON_ERROR_STOP=1 --command "select current_database(), current_user, version();"

db-shell-prod: require-psql
    @just _ensure-env "{{ prod_keys }}"
    @just _db-shell-prod

_db-shell-prod:
    @psql "host=$PGHOST port=$PGPORT dbname=$PGDATABASE user=$PGUSER sslmode=$PGSSLMODE"

db-bootstrap-prod: require-psql
    @test "${CONFIRM_PROD_BOOTSTRAP:-}" = "1" || { echo "Set CONFIRM_PROD_BOOTSTRAP=1 to bootstrap prod."; exit 1; }
    @just _ensure-env "{{ prod_keys }} {{ prod_admin_keys }}"
    @just _db-bootstrap-prod

_db-bootstrap-prod:
    @PGPASSWORD="$POSTGRES_ADMIN_PASSWORD" psql "host=${POSTGRES_ADMIN_HOST} port=${POSTGRES_ADMIN_PORT} dbname=${PGDATABASE} user=${POSTGRES_ADMIN_USER} sslmode=${POSTGRES_ADMIN_SSLMODE}" --set=ON_ERROR_STOP=1 --command "create extension if not exists pgcrypto;" --command "create extension if not exists pg_trgm;" --command "create extension if not exists vector;" --command "grant usage, create on schema public to \"$PGUSER\";"

db-migrate-prod: require-pnpm
    @test "${CONFIRM_PROD_MIGRATE:-}" = "1" || { echo "Set CONFIRM_PROD_MIGRATE=1 to migrate prod."; exit 1; }
    @just _ensure-env "{{ prod_keys }}"
    @just _db-migrate-prod

_db-migrate-prod:
    @pnpm db:migrate

db-seed-prod: require-pnpm
    @test "${CONFIRM_PROD_SEED:-}" = "1" || { echo "Set CONFIRM_PROD_SEED=1 to seed prod."; exit 1; }
    @just _ensure-env "{{ prod_keys }}"
    @just _db-seed-prod

_db-seed-prod:
    @pnpm db:seed

db-studio-prod: require-pnpm
    @just _ensure-env "{{ prod_keys }}"
    @just _db-studio-prod

_db-studio-prod:
    @pnpm db:studio

build-local: require-pnpm
    @DATABASE_URL="{{ local_database_url }}" pnpm build

build-prod: require-pnpm
    @just _ensure-env "{{ prod_keys }}"
    @just _build-prod

_build-prod:
    @pnpm build

typecheck: require-pnpm
    @pnpm typecheck

deploy-prod-db:
    @test "${CONFIRM_PROD_DEPLOY:-}" = "1" || { echo "Set CONFIRM_PROD_DEPLOY=1 to deploy/update the prod RDS stack."; exit 1; }
    @just require-aws
    @just _ensure-env "PGDATABASE {{ prod_rds_keys }}"
    @just _deploy-prod-db

_deploy-prod-db:
    #!/usr/bin/env bash
    set -euo pipefail
    aws cloudformation deploy \
        --region "$AWS_REGION" \
        --stack-name "$RDS_STACK_NAME" \
        --template-file infra/rds/postgres.yml \
        --parameter-overrides \
            DBInstanceIdentifier="$RDS_INSTANCE_IDENTIFIER" \
            DBName="$PGDATABASE" \
            EngineVersion="${RDS_ENGINE_VERSION:-}" \
            DBInstanceClass="$RDS_DB_INSTANCE_CLASS" \
            AllocatedStorage="$RDS_ALLOCATED_STORAGE" \
            MaxAllocatedStorage="$RDS_MAX_ALLOCATED_STORAGE" \
            DBSubnetGroupName="$RDS_SUBNET_GROUP_NAME" \
            VpcSecurityGroupIds="$RDS_SECURITY_GROUP_IDS" \
            PubliclyAccessible="${RDS_PUBLICLY_ACCESSIBLE:-false}" \
            BackupRetentionPeriod="${RDS_BACKUP_RETENTION_DAYS:-7}" \
            MultiAZ="${RDS_MULTI_AZ:-false}" \
            DeletionProtection="${RDS_DELETION_PROTECTION:-true}"
    aws cloudformation describe-stacks \
        --region "$AWS_REGION" \
        --stack-name "$RDS_STACK_NAME" \
        --query "Stacks[0].Outputs" \
        --output table

prod-release:
    @just typecheck
    @just build-prod
    @CONFIRM_PROD_MIGRATE=1 just db-migrate-prod
